In [3]:
# QESTION - 1

import numpy as np

print(np.__version__)

1.18.5


In [13]:
arr = np.arange(start=2, stop=50, step=3)

In [14]:
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [25]:
# QUESTION - 2

n = int(input())
lst1 = []
lst2 = []
for i in range(0,n):
    ele1 = int(input())
    lst1.append(ele1)
for j in range(0,n):
    ele2 = int(input())
    lst2.append(ele2)
arr1 = np.array(lst1)
arr2 = np.array(lst2)
con = np.concatenate((arr1,arr2),axis=0)
print(con)
print(np.sort(con))

5
3
5
1
4
2
8
10
6
9
7
[ 3  5  1  4  2  8 10  6  9  7]
[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
# QUESTIION - 3

print(arr)

print(arr.ndim)

[ 8  6 10  9  7]
1


In [27]:
print(arr.size)

5


In [34]:
# QUESTION - 4

#CONVERTI 1D TO 2D ARRAY

d1 = np.array([1,2,3,4,5,6])
d2 = np.reshape(d1,(-1,3))
print(d2)


[[1 2 3]
 [4 5 6]]


In [41]:
# QUESTION - 5

# VSTACK

a = np.ones((3,3))
b = np.vstack((a,np.array((2,2,2))))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]]


In [44]:
# HSTACK

a = np.ones((3,3))
b = np.array((2,2,2)).reshape(3,1)
print(b)
c = np.hstack((a,b))
print()
print(c)

[[2]
 [2]
 [2]]

[[1. 1. 1. 2.]
 [1. 1. 1. 2.]
 [1. 1. 1. 2.]]


In [45]:
# QUESTION - 6

lst = [1,2,2,5,8,4,4,8]

lst2 = []
count = 0
for item in lst:
    if item not in lst2:
        lst2.append(item)
        count += 1
print('Unique items in a',lst,'is',lst2)
print('Count of unique items is',count)

Unique items in a [1, 2, 2, 5, 8, 4, 4, 8] is [1, 2, 5, 8, 4]
Count of unique items is 5
